import { Metadata } from 'next'

export const defaultMetadata: Metadata = {
  title: 'Mohammed Saket | Full Stack Developer',
  description: 'Experienced Full Stack Developer specializing in React, TypeScript, and modern web technologies. View my portfolio of projects and professional experience.',
  keywords: [
    'Full Stack Developer',
    'React Developer',
    'TypeScript Developer',
    'Web Development',
    'Software Engineer',
    'Frontend Developer',
    'Backend Developer',
    'UI/UX Developer',
    'Portfolio',
    'London Developer',
    'Remote Developer',
    'Presto Labs',
    'TCS',
    'Apple',
    'Eventos Hub',
    'Mohammed Saket',
    'mdsaket',
    'mdsaket.com',
    'Mohammed Saket Portfolio',
    'Mohammed Saket Full Stack Developer',
    'Mohammed Saket React Developer',
    'Mohammed Saket TypeScript Developer',
    'Mohammed Saket Frontend Developer',
    'Mohammed Saket Backend Developer',
    'Mohammed Saket UI/UX Developer',
    'Mohammed Saket Portfolio',
    'Mohammed Saket Full Stack Developer Portfolio',
    'Mohammed Saket React Developer Portfolio',
    'Mohammed Saket TypeScript Developer Portfolio',
  ],
  authors: [{ name: 'Mohammed Saket' }],
  creator: 'Mohammed Saket',
  publisher: 'Mohammed Saket',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL('https://mdsaket.com'),
  alternates: {
    canonical: '/',
  },
  openGraph: {
    title: 'Mohammed Saket | Full Stack Developer',
    description: 'Experienced Full Stack Developer specializing in React, TypeScript, and modern web technologies.',
    url: 'https://mdsaket.com',
    siteName: 'Mohammed Saket Portfolio',
    images: [
      {
        url: '/ms.png',
        width: 1200,
        height: 630,
        alt: 'Mohammed Saket Portfolio',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Mohammed Saket | Full Stack Developer',
    description: 'Experienced Full Stack Developer specializing in React, TypeScript, and modern web technologies.',
    images: ['/ms.png'],
    creator: '@mohammedsaket',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: 'your-google-site-verification',
  },
} 